name: "Brand impersonation: Sublime Security"
description: |
  Possible attempt to impersonate the Sublime Security team.
type: "rule"
source: |
  type.inbound
  and sender.display_name in (
    'Sublime Security',
    'Josh Kamdjou',
    'Joshua Kamdjou',
    'Ian Thiel',
    'Jonathan Bunce',
    'Brian Lee'
  )
  and sender.email.domain.domain != 'sublimesecurity.com'
tags:
  - "brand-impersonation"
  - "contact-impersonation"
  - "suspicious-sender"
